// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRsp struct {
	RetCode int32 `json:"retCode"`
	Token string `json:"token"`
}

type UserInfoReq struct {
	Username string `json:"username"`
}

type UserInfoRsp struct {
	Name string `json:"name"`
}
